# Sample .travis.yml for R projects

language: r
cache: packages
warnings_are_errors: true
sudo: required
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - libgsl0-dev

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh install_deps

env:
  global:
    - R_BUILD_ARGS="--resave-data"
    - R_CHECK_ARGS="--as-cran"
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_="FALSE"
